# Generated by Django 5.2.6 on 2025-10-11 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('last_names', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('personal_info', models.TextField()),
                ('email', models.EmailField(max_length=50)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('user_type', models.CharField(choices=[('COLAB', 'Colaborador'), ('ADMIN', 'Administrador'), ('OWNER', 'Dueño')], max_length=15)),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
