# Generated by Django 5.2.6 on 2025-10-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_usuario_city_usuario_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sex',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
