# Generated by Django 5.2.6 on 2025-10-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_usuario_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='year',
        ),
        migrations.AddField(
            model_name='profession',
            name='courses',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='degree',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='specialization',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profession',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profession',
            name='institution',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
