# Generated by Django 5.2.6 on 2025-10-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_profession_name_remove_profession_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='profession',
        ),
        migrations.AddField(
            model_name='usuario',
            name='courses',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='degree',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='institution',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='specialization',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
    ]
