# Generated by Django 5.2.6 on 2025-10-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_usuario_profession_usuario_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='years_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
