# Generated by Django 5.2.6 on 2025-10-05 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('last_names', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('personal_info', models.TextField()),
                ('email', models.EmailField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
