# Generated by Django 5.2.6 on 2025-10-16 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_usuario_graduation_year_and_more'),
        ('company', '0002_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.usuario'),
        ),
    ]
